### PR TITLE
[RFR] Create demo data during the execution of tests

### PR DESCRIPTION
**Pull request by StefanRijnhart**
This ensures that the demo chart of accounts is already installed when the
bank journal account is created for the bank journal that is needed to
test the import. Otherwise, the demo chart from l10n_generic_coa will fail
to install because there is already a journal account in the system.

https://github.com/OCA/bank-statement-import/pull/79#issuecomment-265771506

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thank you very much! As we can't see the result until this is merged, I fast-track it.

**Comment by pedrobaeza** [comment]
Fixed!!

**Comment by StefanRijnhart** [comment]
Good! Thanks for signalling the problem and taking swift action on this one.

**Comment by pedrobaeza** [comment]
Thanks to you for fixing it!

**Pull request merged**
