### PR TITLE
[16.0][MIG][WIP] account_statement_import_online_gocardless: Migration to 16.0

### PR DESCRIPTION
**Pull request by AlexPForgeFlow**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please add #650

**Comment by pedrobaeza** [comment]
Add #652 as well

**Comment by njeudy** [comment]
@pedrobaeza is there a way to continue and finish this PR @AlexPForgeFlow any news for this PR ? I can try to apply what pedro said .. or review if you do the job.

**Comment by AlexPForgeFlow** [comment]
> PR ?

I'm closing this PR, @njeudy you can continue the migration from mine

**Pull request closed without merging**
