### PR TITLE
[11.0][MIG] account_bank_statement_import_online

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Backport from v12

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@pedrobaeza in backports or forwardports, version upgrade commits should be dropped?

**Comment by pedrobaeza** [comment]
I don't get you. Do you mean migration scripts?

**Comment by alexey-pelykh** [comment]
@pedrobaeza should I keep or drop commits like `account_bank_statement_import_online 12.0.1.4.0` that are done by bot?

**Comment by pedrobaeza** [comment]
Squash always administrative commits like that one with previous significant commit:

Selección_005

**Comment by alexey-pelykh** [comment]
@pedrobaeza like that?

**Comment by pedrobaeza** [comment]
It seems so

**Review by ivs-cetmix — APPROVED** [review]
Looks reasonable

**Pull request merged**
