### PR TITLE
[17.0][MIG] account_statement_import_sheet_file: Migration to 17.0

### PR DESCRIPTION
**Pull request by rov-adhoc**
Depends on:

- [649] https://github.com/OCA/bank-statement-import/pull/649

### CODE REVIEW

**Comment by xtanuiha** [comment]
I have contributed translations for Simplified Chinese, could you please merge them to your code, thank you! @rov-adhoc 

[zh_CN.zip](https://github.com/OCA/bank-statement-import/files/14917059/zh_CN.zip)

**Comment by pedrobaeza** [comment]
That should be added on Weblate once the module is merged.

**Comment by pedrobaeza** [comment]
To add: #693

**Comment by peluko00** [comment]
Could you continue @rov-adhoc ?

**Comment by rov-adhoc** [comment]
@peluko00 done

**Comment by peluko00** [comment]
> @peluko00 done

Thanks!

**Review by peluko00 — APPROVED** [review]
Works good, tested in runboat. LGTM

**Review by javierobcn — APPROVED** [review]
Running

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
