### PR TITLE
[12.0][ADD] account_bank_statement_import_online_paypal

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Adds online bank statements from PayPal

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@pedrobaeza potentially, online sync is also interesting for Tecnativa

**Comment by pedrobaeza** [comment]
Well, this is used for OCA instance, so @OSevangelist should say if they are going to use this or the traditional file import.

**Comment by alexey-pelykh** [comment]
@OSevangelist it would be awesome to understand if that's useful for you

**Review by artemsenko — APPROVED** [review]
functional tests

**Review by sweenya — APPROVED** [review]
Functional test

**Review by sweenya — APPROVED** [review]
Functional test

**Comment by rvalyi** [comment]
@alexey-pelykh I'm following your online bank statetement import work with interest. But for this particular Paypal case, I was wondering if no logic could be shared between this new module and the existing one which works from the file (and not via API):
https://github.com/OCA/bank-statement-import/tree/12.0/account_bank_statement_import_paypal
Then may be some refactor is possible instead of duplicating the mapping logic. Frankly I don't know, just asking.

**Comment by alexey-pelykh** [comment]
@rvalyi thanks! I've looked into that module in terms of sharing code and there's even a #236 regarding it. My conclusion is: not worthy, data structures are different

**Comment by rvalyi** [comment]
ok thank you for this analysis and the other PR. I pinged @sebastienbeau who is the person most skilled on these modules at Akretion.

**Comment by alexey-pelykh** [comment]
@OCA/banking-maintainers would it be possible to make further steps about this module?

**Comment by rafaelbn** [comment]
Are you using this PR in production?

**Comment by alexey-pelykh** [comment]
@rafaelbn yep, though we’re using PayPal less often than before. On top of that, PayPal has some glitch on every Monday’s start of day that causes false-positive error message, their engineers are looking into that right now

**Comment by alexey-pelykh** [comment]
The issue is confirmed to be on PayPal side, nothing to be fixed in the module itself, so I'll just merge it.

**Pull request merged**
