### PR TITLE
[10.0][FIX] account_bank_statement_import_camt: switch name and note

### PR DESCRIPTION
**Pull request by astirpe**
Fixes https://github.com/OCA/bank-statement-import/issues/176

### CODE REVIEW

**Review by sbidoul — APPROVED** [review]

**Review by yung-wang — APPROVED** [review]
It works great for us

**Review by ThomasBinsfeld — APPROVED** [review]

**Review by PatrickMallee — APPROVED** [review]
works fine

**Comment by mkusmic** [comment]
Looks like this would solve the same problem we had with CAMT.053 import and <RmtInf><Ustrd> not showing up in name/communication field.

**Comment by pedrobaeza** [comment]
It should be forward-ported to v11

**Comment by astirpe** [comment]
@pedrobaeza here is the PR https://github.com/OCA/bank-statement-import/pull/179

**Pull request merged**
