### PR TITLE
[11.0][FIX] account_bank_statement_import_paypal: fuzzy ES locale

### PR DESCRIPTION
**Pull request by alexey-pelykh**
@pedrobaeza @sbidoul please fix the strategy as discussed in #282, this is just insane

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
Travis is under maintenance, probably that's why it's stuck?

**Comment by pedrobaeza** [comment]
Not sure, but it can be

**Comment by alexey-pelykh** [comment]
It seems to be very stuck https://travis-ci.org/github/OCA/bank-statement-import/builds/678294694

**Comment by sbidoul** [comment]
oof, curious to see what's going to happen now :)

**Comment by sbidoul** [comment]
Good bot :)

**Pull request merged**
