### PR TITLE
[12.0] [MIG] account bank statement import ofx

### PR DESCRIPTION
**Pull request by benj-filament**
Port bank account statement import ofx from v11.0

### CODE REVIEW

**Comment by alexis-via** [comment]
with ofxparse 0.17 I get this error:
```
  File "/home/alexis/new_boite/dev/bank-statement-import2/account_bank_statement_import_ofx/wizard/account_bank_statement_import.py", line 87, in _parse_file
    balance = float(ofx.account.statement.balance)
```
I had to change that line of code to use ofx.account.statement.available_balance
But I don't have time at the moment to look further...

**Comment by eLBati** [comment]
@benj-filament thanks.
Please fix the old commits where you are the committer with `Benjamin <Benjamin@MBP-de-Benj.(none)>`

**Comment by remi-filament** [comment]
Thank you for testing it @alexis-via 
You probably are missing the <LEDGERBAL> tag (which are the ones parsed as balance) in your OFX file you are trying to import.
According to spec (see http://www.ofx.org/downloads/OFX%202.2.pdf page 208), these tags are required in OFX file, when AVAILBAL (parsed as available_balance) are optional.

**Comment by remi-filament** [comment]
Thank you @eLBati , it took me some time to find out where this e-mail was and how to fix the committer, but it should be OK now.

**Review by remi-filament — APPROVED** [review]
LGTM

**Review by alexis-via — APPROVED** [review]

**Pull request merged**
