### PR TITLE
[12.0][ADD] account_bank_statement_import_split

### PR DESCRIPTION
**Pull request by alexey-pelykh**
This module allows splitting statements by date during import:

* as daily statements
* as weekly statements
* as monthly statements

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@pedrobaeza @aheficent @etobella I'd like to kindly ask for a slice of your time to check in this module

**Review by etobella — APPROVED** [review]
LGTM :+1: Code reviewed

**Review by artemsenko — APPROVED** [review]
functional test

**Comment by alexey-pelykh** [comment]
@sbidoul @pedrobaeza good to go?

**Comment by sbidoul** [comment]
LGTM

/ocabot merge

**Pull request merged**
