### PR TITLE
[12.0][FIX] account_bank_statement_import_paypal: fuzzy es locale

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@pedrobaeza again I'm fighting with translations :| did I get it right this time?

**Comment by pedrobaeza** [comment]
I'm not seeing placeholders this time, so it shouldn't be a problem AFAIK. Just incorrect translations. Did you regenerate es.po or was it the automatic system?

**Comment by alexey-pelykh** [comment]
I only edited `es.po` manually. Issue is different this time - when user has Spanish locale, importing does not work for some reason, having English locale - it works. I assume it has something to do with "translation" of system fields of view or something like that

**Comment by alexey-pelykh** [comment]
> Did you regenerate es.po or was it the automatic system?

Please elaborate on this

**Comment by pedrobaeza** [comment]
How that es.po has ended here? Due to you opening es.po in POEdit and updating from template or it has been OCA automatic processes?

**Comment by alexey-pelykh** [comment]
Oh, I think it was just here always, I have not created it in any manner.

**Comment by pedrobaeza** [comment]
Then maybe something must be adjusted in the automatic part. See the commit history for understanding this:

https://github.com/OCA/bank-statement-import/commits/12.0/account_bank_statement_import_paypal/i18n/es.po

The file is automatically adjusted when the POT changes.

@sbidoul isn't there a strict pomerge for not allowing fuzzy search to match strings?

**Comment by pedrobaeza** [comment]
Any way, let's merge this cleaning:

/ocabot merge nobump

**Comment by sbidoul** [comment]
> isn't there a strict pomerge for not allowing fuzzy search to match strings?

@pedrobaeza I think it is configurable in weblate, yes. Not sure what the best strategy is in general, though.

**Comment by pedrobaeza** [comment]
We can see here that is not the best one, as it makes a "best match" option, but the content differs significantly. Can you please check or tell me where to see?

**Pull request merged**
