### PR TITLE
10.0 account bank statement import camt

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Mainly cherry-picking from the 9.0 branch, and a trivial migration in https://github.com/StefanRijnhart/bank-statement-import/commit/a042184385243b4574ba82f2c376499c9d17f5d5

### CODE REVIEW

**Review by hbrunn — APPROVED** [review]

**Review by pedrobaeza — COMMENTED** [review]
Tentatively :+1:, waiting for Travis result, but we should integrate also #77

**Comment by andrius-preimantas** [comment]
:+1: tested and it works perfectly.

**Comment by pedrobaeza** [comment]
@StefanRijnhart there are conflicts in files, possible because you cherry-pick commits instead of following migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

**Comment by StefanRijnhart** [comment]
@pedrobaeza Sorry about that. I overwrote this branch by another migration using the preferred method instead of cherrypicking.

**Comment by pedrobaeza** [comment]
No need to apologize, merging...

**Pull request merged**
