### PR TITLE
IMP account_bank_statement_import_camt: handle transaction grouping in camt files

### PR DESCRIPTION
**Pull request by eLBati**
ported from https://github.com/OCA/bank-statement-import/pull/102

### CODE REVIEW

**Comment by eLBati** [comment]
This has been validated by our customers. Please review

**Comment by melroy89** [comment]
It's a backport right?

**Review by gurneyalex — APPROVED** [review]

**Review by simahawk — APPROVED** [review]

**Comment by leemannd** [comment]
@danger89 Yes, it seems so

**Comment by eLBati** [comment]
@danger89 right

**Review by leemannd — APPROVED** [review]

**Pull request merged**
