### PR TITLE
[16.0][MIG] account_statement_import_base

### PR DESCRIPTION
**Pull request by alexis-via**
Now depend on account_statement_base from https://github.com/OCA/account-reconcile/pull/514
Related to discussion on https://github.com/OCA/account-reconcile/pull/500

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]
code review + tests
(the CI tests will require https://github.com/OCA/account-reconcile/pull/514 to get merged to pass though)

**Review by AntoniRomera — APPROVED** [review]

**Review by leemannd — APPROVED** [review]

**Comment by remi-filament** [comment]
This module is already included in #535 (except for the dependency added on account_statement_base).
How should we proceed ? Merge this PR and remove this module from #535 ?

**Comment by florian-dacosta** [comment]
I think we can merge this one once green and adapt the other PR to remove the module.

**Comment by alexis-via** [comment]
I fixed the test error via this PR: https://github.com/OCA/account-reconcile/pull/533

**Comment by alexis-via** [comment]
Same player, try again https://github.com/OCA/account-reconcile/pull/534

**Comment by alexis-via** [comment]
Sorry for all the noise, but we made it at last!

**Comment by Gelo-fl** [comment]
Hi @dreispt,

This module is merged, however the translations are locked:
[bank-statement-import-16.0-account_statement_import_base](https://translation.odoo-community.org/projects/bank-statement-import-16-0/bank-statement-import-16-0-account_statement_import_base/)

Can I know why?

Thanks in advance,

**Comment by pedrobaeza** [comment]
I have unlocked it.

**Pull request merged**
