### PR TITLE
[12.0][IMP] account_bank_statement_import_paypal

### PR DESCRIPTION
**Pull request by alexey-pelykh**
This PR refactors PayPal reports importing:

- support for both statement and activity reports
- extract fees for transactions with more details
- remove hidden currency conversions, as PayPal currencies should be handled by different journals

CC @pedrobaeza @sbidoul @alexis-via

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@pedrobaeza who could help me out with this? Or there's nobody who's interested in this?

**Comment by pedrobaeza** [comment]
Not sure, as I have only one customer using it and it's working, and the other one is OCA itself, which uses also as is.

**Comment by alexey-pelykh** [comment]
Gotcha, in this case would Tecnativa opt-in for checking if this PR improves usecase of the customer?

**Comment by pedrobaeza** [comment]
Please tell me what this improves and what will be need for adapting old mapping to new one.

**Comment by alexey-pelykh** [comment]
It's pretty much as per description in first message:
- support for both statement and activity reports
- extract fees for transactions with more details
- remove hidden currency conversions, as PayPal currencies should be handled by different journals

yet migration of mapping would be tough - it's very different, and not sure if that's even worthy to do that. But having no migration is bad :(

**Comment by pedrobaeza** [comment]
I'm afraid we are not using that features.

**Comment by rvalyi** [comment]
cc @sebastienbeau

**Review by YegorOkhotnikov — APPROVED** [review]
Functional test

**Review by sweenya — APPROVED** [review]
Functional test

**Comment by alexey-pelykh** [comment]
Discussed with Pedro, since the migration script is there, should merge

**Pull request merged**
