### PR TITLE
[16.0][IMP] account_statement_import_sheet_file: add quote as thousand separator

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
Thanks for the contribution! The only thing I wonder if that should be called a prime (') vs apostrophe (’) instead of quote (“) vs double-prime (")

**Review by syera94 — APPROVED** [review]

**Comment by alexis-via** [comment]
@alexey-pelykh I have no idea about the exact wording. No problem to change it.

**Review by luisDIXMIT — APPROVED** [review]
LGTM

**Review by hbrunn — APPROVED** [review]

**Pull request merged**
