### PR TITLE
[10.0] allow camt054 to be parsed

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Review by astirpe — APPROVED** [review]

**Comment by astirpe** [comment]
@eLBati shouldn't the module description in the README be updated accordingly?
It actually says:

```
Module to import SEPA CAMT.053 Format bank statement files.
```

You should also bump the module version.

**Comment by eLBati** [comment]
@astirpe done, thanks

**Review by ecino — APPROVED** [review]

**Review by melroy89 — APPROVED** [review]
Merge

**Comment by BT-nfrei** [comment]
Hello @eLBati ,
Thank you for this, this is certainly useful! I think two lines should be updated to reflect the changes (ErrorMessage and docstring):
line 223: `raise ValueError('no camt 052 or 053: ' + ns)`
line 230: `"""Parse a camt.052 or camt.053 file."""`
Other than that, I'm looking forward to the merge.

**Comment by alexis-via** [comment]
@eLBati Could you update the error message in camt.py line 230, as explained by @BT-nfrei ? Then I'll merge this PR.

**Comment by eLBati** [comment]
@alexis-via @BT-nfrei done, thanks

**Review by alexis-via — APPROVED** [review]

**Pull request merged**
