### PR TITLE
[17.0][MIG] account_statement_import_camt: Migration to 17.0

### PR DESCRIPTION
**Pull request by hbrunn**
Depends:

- [ ] https://github.com/OCA/bank-statement-import/pull/649 (included here for simplicity of testing)

/ocabot migration account_statement_import_camt

### CODE REVIEW

**Review by luc-demeyer — APPROVED** [review]
code review & testing ok

**Review by sebalix — APPROVED** [review]

**Comment by yankinmax** [comment]
hello @hbrunn, can you please rebase? 
`account_statement_import_file` is merged here:
- [ ] https://github.com/OCA/bank-statement-import/pull/692

**Review by yankinmax — APPROVED** [review]

**Comment by hbrunn** [comment]
@yankinmax thanks for the heads-up, done

**Comment by AquaMCU** [comment]
Hi. Do you know when this PR will be integrated?

**Review by xaviedoanhduy — APPROVED** [review]

**Review by MarwanBHL — APPROVED** [review]

**Review by grindtildeath — APPROVED** [review]

**Pull request merged**
