### PR TITLE
[12.0][account_bank_statement_import_txt_xlsx, account_bank_statement_import_paypal] fixes broken views

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Adjust wizard after https://github.com/OCA/server-ux/pull/165 has been merged.

cc @alexey-pelykh

### CODE REVIEW

**Review by alexey-pelykh — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
image
@JordiBForgeFlow it seems that it needs a bit more changes

**Review by alexey-pelykh — CHANGES_REQUESTED** [review]
"Import" button then is no longer needed and it's handling may be moved to "Next" button

**Comment by JordiBForgeFlow** [comment]
I'm confused on why do we need to use the multi_step_wizard in those modules, if in this case we just need one step. Am I missing something here?

**Comment by alexey-pelykh** [comment]
@JordiBForgeFlow there are two steps: file import and mapping configuration

**Comment by JordiBForgeFlow** [comment]
@alexey-pelykh ok. Will look into it then.

**Comment by JordiBForgeFlow** [comment]
Ok, I now show the import statement button only in the final step. Does it look right to you now @alexey-pelykh ?

**Comment by JordiBForgeFlow** [comment]
@alexey-pelykh It's a bit weird that after importing the file and creating the mapping the wizard window is not closed. But I'm not sure if this was already happening before, or it's a regression introduced by this PR.

**Comment by alexey-pelykh** [comment]
@JordiBForgeFlow or it's a multi_step_wizard regression, I don't recall such behaviour, it should've been closed, naturally

**Comment by alexey-pelykh** [comment]
Try adding `return {'type': 'ir.actions.act_window_close'}` to `import_mapping` maybe, and please adjust the commit history (or even split the PRs) so that changes would be atomic, I guess

**Comment by JordiBForgeFlow** [comment]
@alexey-pelykh I now have split into two separate commits to clearly distinguish the changes to each module.

**Comment by JordiBForgeFlow** [comment]
@alexey-pelykh instead of doing a window close I am redirecting the user to the new record once the import has happened.

**Comment by JordiBForgeFlow** [comment]
I'm merging this one as currently stable 12.0 is broken.

**Comment by JordiBForgeFlow** [comment]
@alexey-pelykh I guess that you need to approve the changes you requested before I can merge.

**Review by alexey-pelykh — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
Ocabot just sleeps probably :) It reacts sometimes hours later

**Pull request merged**
