### PR TITLE
[14.0] [FIX] ponto import

### PR DESCRIPTION
**Pull request by NL66278**
Alternative attempt to fix Ponto import (problem of missing data), without buffering.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Yes, please let's go with this one instead of the buffer one. cc @alexis-via @alexey-pelykh

**Comment by pedrobaeza** [comment]
Can you simplify the commit history a bit for not adding and then removing things?

**Comment by NL66278** [comment]
@pedrobaeza There are now just two commits left.

**Review by pedrobaeza — APPROVED** [review]
@alexis-via is it OK for you?

**Review by njeudy — APPROVED** [review]
Just tested on a copy of production database, and check code . Ok for me.

**Comment by pedrobaeza** [comment]
Let's merge it then:

/ocabot merge nobump

Can you do the fw-port?

**Comment by pedrobaeza** [comment]
Seeing that the PR already contains the version bump:

/ocabot merge nobump

@NL66278 it's not needed to do it, as the bot does it and there's no migration scripts.

**Pull request merged**
