### PR TITLE
[RFR] Don't unzip xlsx files

### PR DESCRIPTION
**Pull request by StefanRijnhart**
The 'ask forgiveness' strategy does not work when the import file can actually be unzipped but shouldn't. I'm proposing a slight refactoring that allows overriding customizations to judge by themselves if they want to allow unzipping.

### CODE REVIEW

**Comment by melroy89** [comment]
also not merged? This is almost 1 year old...!?

**Comment by pedrobaeza** [comment]
@danger89 this is because nobody including you has reviewed the PR.

**Comment by StefanRijnhart** [comment]
@danger89 yes, please review my work. It will motivate me to do more reviews myself on this project.

**Review by melroy89 — APPROVED** [review]
Is this also a good feature for newer branches, v10/v11? Or are the differences too big?

**Comment by StefanRijnhart** [comment]
I'm sure porting to newer branches will be easy.

**Review by NL66278 — APPROVED** [review]
:+1: LGTM Usefull enhancement.

**Pull request merged**
