### PR TITLE
[MIG] account_statement_import_txt_xlsx: Migration to 16.0

### PR DESCRIPTION
**Pull request by zaoral**

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@zaoral could you redo again the commit history? 🙏  new commits have been merged in v15.

**Comment by hitrosol** [comment]
i try this on my local and it works well. Any plan to make the test green ?

**Comment by jumeldi74** [comment]
I'll try to fix the error on it's unit test

**Comment by maxgrassi** [comment]
I tested with CSV and xlsx file  and I get this warning message: "This bank statement file format is not supported.
Did you install the Odoo module to support this format?" The module is installed.  I provide the test file I'm using if it helps to reproduce the problem. Can you check and let me know please ? I also tested on runboat for V15 and I get same warning message. 
[EC-TEST.csv](https://github.com/OCA/bank-statement-import/files/12250061/EC-TEST.csv)

**Comment by victoralmau** [comment]
Please, cherry-pick https://github.com/OCA/bank-statement-import/pull/619 to commit history

**Comment by MiquelRForgeFlow** [comment]
And https://github.com/OCA/bank-statement-import/commit/712301a96452d01a13b7644208e44c3017a7606a.

**Comment by heroic** [comment]
@zaoral @victoralmau @MiquelRForgeFlow added the cherry picks here: https://github.com/adhoc-dev/bank-statement-import/pull/1

Can someone merge these?

**Comment by mostafabarmshory** [comment]
Log is not available any more. It is expired and removed from github.

What the problem is? How can I help to fix the issue?!

**Comment by victoralmau** [comment]
Superseed by https://github.com/OCA/bank-statement-import/pull/628

**Pull request closed without merging**
