### PR TITLE
[MIG][14.0] account_statement_import_camt

### PR DESCRIPTION
**Pull request by i-vyshnevska**
depends https://github.com/OCA/bank-statement-import/pull/367

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think this should be renamed to `account_statement_import_camt` following the new nomenclature.

**Review by StephaneMangin — APPROVED** [review]
LGTM

**Review by gurneyalex — APPROVED** [review]

**Comment by gurneyalex** [comment]
@i-vyshnevska #367  is merged, can you rebase?

**Comment by i-vyshnevska** [comment]
@gurneyalex renamed and squashed

**Comment by pedrobaeza** [comment]
For a deep rename (if not, the commit history will be lost in next version), I use:
```
git filter-branch --tree-filter 'if [ -d $old_module_name ]; then mv $old_module_name $new_module_name; fi' HEAD
```
and after that a rebase.

**Comment by i-vyshnevska** [comment]
@pedrobaeza I tried to follow your advice regards commit history but this leads to messing in git history and autoclosing this PR so I needed to reopen it

**Comment by pedrobaeza** [comment]
OK, don't worry about it.

**Comment by i-vyshnevska** [comment]
@pedrobaeza thanks, can we progress on merging https://github.com/OCA/bank-statement-import/pull/369?

**Comment by pedrobaeza** [comment]
I'm afraid I can't give functional feedback.

**Comment by i-vyshnevska** [comment]
@pedrobaeza https://github.com/OCA/bank-statement-import/pull/362 and https://github.com/OCA/bank-statement-import/pull/369
are the same, 362 was approved and closed on my mistake

**Pull request closed without merging**
