### PR TITLE
The import must fail if the bank_account or the account_journal is no…

### PR DESCRIPTION
**Pull request by lmignon**
…t found

The creation of account_journal and bank_account must be prohibited when importing statments.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please check Travis test error?

**Comment by lmignon** [comment]
@pedrobaeza of course

**Comment by pedrobaeza** [comment]
Thanks :+1:

**Comment by sbidoul** [comment]
:+1:

**Comment by lmignon** [comment]
@pedrobaeza @sbidoul Sorry for the commit after your reviews but I forgot to bump the version number...

**Comment by pedrobaeza** [comment]
Don't worry, the correct thing is to bump the version. I always forget it.

**Comment by adrienpeiffer** [comment]
:+1: (Code review)

**Pull request merged**
