### PR TITLE
[8.0][FIX] Start/end balance on OFX statement

### PR DESCRIPTION
**Pull request by alexis-via**
This is just a "go back" to the code before this commit: https://github.com/OCA/bank-statement-import/commit/c7c6954df7d1932afe539a17c855cb87acec70b3

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Hi @alexis-via, thank you. This does raise some questions. Is this  bug present on the origin 10.0 branch as well? Why is the start and end balance in the test the same amount?
cc. @lmignon

**Comment by StefanRijnhart** [comment]
Self answering my first question: https://github.com/OCA/bank-statement-import/pull/90

**Comment by alexis-via** [comment]
@StefanRijnhart Answering your second question: in the test OFX file, start and end balance are NOT the same: 2516.56 vs 2156.56... look carefully at the second digit :-)

**Review by StefanRijnhart — APPROVED** [review]
I Need new glasses!

**Pull request merged**
