### PR TITLE
[12.0][FIX] account_bank_statement_import_paypal: adjust TZ mapping

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Addressing #312

### CODE REVIEW

**Comment by pedrobaeza** [comment]
CEST is not the same as CET. Why do you change it?

**Comment by alexey-pelykh** [comment]
@pedrobaeza because there's no such timezone in tz database:
image

**Comment by pedrobaeza** [comment]
https://stackoverflow.com/questions/10913986/correctly-parse-date-string-with-timezone-information

**Comment by alexey-pelykh** [comment]
image

**Comment by pedrobaeza** [comment]
I don't get you... The solution I saw in the link is to put "Europe/Madrid" for example as tz

**Comment by alexey-pelykh** [comment]
Ah, I didn't get that right. You mean to use Paris or Madrid as a replacement?

**Comment by pedrobaeza** [comment]
Yes, I think it can work.

**Comment by alexey-pelykh** [comment]
Done

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
