### PR TITLE
12.0 backport account bank statement import guess partner

### PR DESCRIPTION
**Pull request by ntsirintanis**
Related; https://github.com/OCA/bank-statement-import/pull/456

### CODE REVIEW

**Comment by ntsirintanis** [comment]
@NL66278 now tests are not failing, but still failing on 13.0 version. I'll push another commit there, and check to fix codecov too

**Review by NL66278 — APPROVED** [review]
:+1: Thanks for backporting this!

**Comment by NL66278** [comment]
@alexis-via Could you have a look at this one? Is working well in production, but would be nice to have this merged, For some reason runboat did not run.

**Comment by NL66278** [comment]
@ntsirintanis Could you rebase this on latest 12.0? This will probably solve the runboat issue.

**Pull request closed without merging**
