### PR TITLE
[8.0][ADD] Improved module base_bank_account_number_unique.

### PR DESCRIPTION
**Pull request by NL66278**
Re-implement the checks for uniqueness. Now allowing for duplicate if one is for company account, another for partner (which might be the other company in a multicompany database). Check now uses @constrains rather then SQL Unique index. Adding company_id to the unique index makes no sense as most rows contain NULL values for company_id, so these would always be considered unequal.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
I did some [more tests](https://github.com/lbeopennet/bank-statement-import/tree/8.0%2B117%2Bmore_tests) and it [held up fine.](https://travis-ci.org/lbeopennet/ci-staging/builds/253533784) Very tidy, and your rationale for doing it in the ORM is correct.

LGTM

**Comment by NL66278** [comment]
@lbeopennet Maybe you want to add your extra test to the branch? You could do a PR to my branch, extra tests look very usefull to me.

**Comment by ghost** [comment]
@NL66278 as you wish

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Merging this has result in LINT errors:
```
base_bank_account_number_unique/README.rst:27: [E7901(rst-syntax-error), ]  Definition list ends without a blank line; unexpected unindent.
base_bank_account_number_unique/README.rst:28: [E7901(rst-syntax-error), ]  Definition list ends without a blank line; unexpected unindent.
base_bank_account_number_unique/README.rst:30: [E7901(rst-syntax-error), ]  Unexpected indentation.
base_bank_account_number_unique/README.rst:33: [E7901(rst-syntax-error), ]  Definition list ends without a blank line; unexpected unindent.
base_bank_account_number_unique/README.rst:35: [E7901(rst-syntax-error), ]  Block quote ends without a blank line; unexpected unindent.
base_bank_account_number_unique/README.rst:35: [E7901(rst-syntax-error), ]  Unexpected possible title overline or transition.|Treating it as ordinary text because it's so short.
```
Can you please fix them?

**Comment by NL66278** [comment]
@pedrobaeza I do not know how the merge brought this about. In the original README.rst, which you can still see in my branch, the piece of SQL starts with a double colon, that is for literal text quotations: ```::```. In the merged code this is replaced with a dot: ```.```.

I will submit a PR to try to rectify this, but do not know wether this will not result in the same problem when merged....

**Comment by NL66278** [comment]
Here it is: https://github.com/OCA/bank-statement-import/pull/172

**Pull request merged**
