### PR TITLE
[IMP] account_statement_import_camt: look for currency under Ntry

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Encountered in a Camt.054 statement: currency listed under
/BkToCstmrDbtCdtNtfctn/Ntfctn/Ntry/Amt/@Ccy

### CODE REVIEW

**Comment by TeoGoddet** [comment]
See #426 and #388 
Issue #387 also

**Review by sebalix — APPROVED** [review]
Because of the added test I would favor this PR instead of #388 388
EDIT: the #426 seems also complete... I haven't enough skills on this addon to know which one is better. Some PSC members could check?

**Comment by anedisi** [comment]
@sebalix those two are independent, this should come on top of that @TeoGoddet from  #426

**Comment by StefanRijnhart** [comment]
I'll have a look at #426 tomorrow to see if it obsoletes this change.

**Comment by StefanRijnhart** [comment]
When I run #426 with the test from this PR, the test fails on
```
2022-04-12 06:47:22,585 1852340 ERROR 14camt odoo.addons.account_statement_import_camt.tests.test_import_bank_statement: ERROR: TestParser.test_parse_camt054
Traceback (most recent call last):
  File "//home/odoo/14.0/parts/bank-statement-import/account_statement_import_camt/tests/test_import_bank_statement.py", line 50, in test_parse_camt054
    self._do_parse_test("test-camt054", "golden-camt054.pydata")
  File "//home/odoo/14.0/parts/bank-statement-import/account_statement_import_camt/tests/test_import_bank_statement.py", line 27, in _do_parse_test
    res = self.parser.parse(data.read())
  File "//home/odoo/14.0/parts/bank-statement-import/account_statement_import_camt/models/parser.py", line 335, in parse
    statement = self.parse_statement(ns, node)
  File "//home/odoo/14.0/parts/bank-statement-import/account_statement_import_camt/models/parser.py", line 286, in parse_statement
    transactions.extend(self.parse_entry(ns, entry_node, result["currency"]))
KeyError: 'currency'
```

When I apply the single line fix from this PR, all tests succeed again. So the PRs are unrelated.

**Review by NL66278 — APPROVED** [review]
:LGTM

**Comment by StefanRijnhart** [comment]
Port to 15: https://github.com/OCA/bank-statement-import/pull/466

**Pull request merged**
