### PR TITLE
[16.0][MIG] account_bank_statement_import_online_qonto > account_statement_import_online_qonto: Migration to version 16.0

### PR DESCRIPTION
**Pull request by carolinafernandez-tecnativa**
- Standard migration from v13 to v16.

@Tecnativa
TT46556

@victoralmau @pedrobaeza

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This should be renamed with full history to `account_statement_import_online_qonto`. Commands:

```
git filter-branch --tree-filter 'if [ -d old_module_name ]; then mv old_module_name new_module_name; fi' HEAD
git rebase origin/branch
```

**Comment by carolinafernandez-tecnativa** [comment]
> This should be renamed with full history to `account_statement_import_online_qonto`. Commands:
> 
> ```
> git filter-branch --tree-filter 'if [ -d old_module_name ]; then mv old_module_name new_module_name; fi' HEAD
> git rebase origin/branch
> ```

done, thanks :)

**Review by pedrobaeza — APPROVED** [review]

**Review by victoralmau — APPROVED** [review]

**Pull request merged**
