### PR TITLE
[13.0][MIG] account_bank_statement_import_ofx

### PR DESCRIPTION
**Pull request by rpsjr**
checked out the branch [13.0][MIG] account_bank_statement_import_ofx #295 and added an extra commit to pass the pre-commit test.

I did it properly @rvalyi?

### CODE REVIEW

**Comment by rvalyi** [comment]
@rpsjr it's much better but still not correct. In your commit, you should only add and commit files under  the account_bank_statement_import_ofx folder, nothing outside. As the moment you added other files likes from the setup folder. These files should not be added in the PR! Instead they will be properly re-generated by the ocabot.

Especially, as you can read in the PR checks, the files setup/_metapackage/VERSION.txt and setup/_metapackage/setup.py conflict with the OCA repo files.

So please do you commit again but only with the files from account_bank_statement_import_ofx and then it should be all good. And if it OK next time I approve it.

**Comment by rpsjr** [comment]
> @rpsjr it's much better but still not correct. In your commit, you should only add and commit files under the account_bank_statement_import_ofx folder, nothing outside. As the moment you added other files likes from the setup folder. These files should not be added in the PR! Instead they will be properly re-generated by the ocabot.
> 
> Especially, as you can read in the PR checks, the files setup/_metapackage/VERSION.txt and setup/_metapackage/setup.py conflict with the OCA repo files.
> 
> So please do you commit again but only with the files from account_bank_statement_import_ofx and then it should be all good. And if it OK next time I approve it.

@rvalyi I would like to say that I apraciate ur patience in guiding me.

So on, I hope this PR is ready to merge now.

**Review by rvalyi — APPROVED** [review]
You nailed it finally. Thanks.

**Comment by rvalyi** [comment]
@BT-fgarbely @alexis-via as you guys were working on #295  you might consider reviewing this PR which fixes the pre-commit tests.

cc @njeudy

**Pull request merged**
