### PR TITLE
[16.0] [MIG] account_statement_import_camt: Migrate to version 16.0

### PR DESCRIPTION
**Pull request by sonhd91**
**Depended on:**
* https://github.com/OCA/account-reconcile/pull/514
* https://github.com/OCA/bank-statement-import/pull/550
* https://github.com/OCA/bank-statement-import/pull/575

**Port fw from 14.0:**
* https://github.com/OCA/bank-statement-import/pull/438
* https://github.com/OCA/bank-statement-import/pull/560

### CODE REVIEW

**Comment by yankinmax** [comment]
@sonhd91 pls rebase on the latest 16.0 updates. pre-commit should be fixed now

**Comment by sonhd91** [comment]
> @sonhd91 pls rebase on the latest 16.0 updates. pre-commit should be fixed now

Branch updated, thank you

**Comment by StephaneMangin** [comment]
cc @sonhd91 You have to change one of your dependency from https://github.com/OCA/bank-statement-import/pull/535 to https://github.com/OCA/bank-statement-import/pull/575 and this PR will be good

**Comment by sonhd91** [comment]
> cc @sonhd91 You have to change one of your dependency from #535 to #575 and this PR will be good

Hi @StephaneMangin, I updated the PR, please check again

**Comment by StephaneMangin** [comment]
cc @sonhd91 Wait for the dependency [PR](https://github.com/OCA/bank-statement-import/pull/575) to be merge until you could update your PR to merge please

**Comment by StephaneMangin** [comment]
For the PR dependency, please take in account this comment https://github.com/OCA/edi/pull/724#issuecomment-1461765822

**Comment by sonhd91** [comment]
> For the PR dependency, please take in account this comment [OCA/edi#724 (comment)](https://github.com/OCA/edi/pull/724#issuecomment-1461765822)

Thank for the update, I removed test-requirements commit, please check again

**Comment by astirpe** [comment]
@sonhd91 there are some conflicts now, could you check?

**Comment by sonhd91** [comment]
> @sonhd91 there are some conflicts now, could you check?

Conflict resolved

**Review by leemannd — APPROVED** [review]

**Review by StephaneMangin — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
Please check https://github.com/OCA/bank-statement-import/pull/560. It seems an obvious and important fix.

**Comment by nagybal** [comment]
Importing the camt file seems to be successful but it imports the starting and ending balance only. I do not see the "Reconcile x Items" anywhere on the dashboard.

If I am on the community version. Do I need to activate another module for the reconciliation feature?

**Comment by StefanRijnhart** [comment]
@nagybal that would be https://github.com/OCA/bank-statement-import/pull/576

**Comment by nagybal** [comment]
> @nagybal that would be #576

I would love to test #556, #576 is missing account_reconcile_oca module. Where can I find it?

**Comment by StefanRijnhart** [comment]
@nagybal https://github.com/OCA/account-reconcile/tree/16.0/account_reconcile_oca

**Comment by sonhd91** [comment]
> Importing the camt file seems to be successful but it imports the starting and ending balance only. I do not see the "Reconcile x Items" anywhere on the dashboard.
> 
> If I am on the community version. Do I need to activate another module for the reconciliation feature?

Sorry for waiting, I'm working on it

**Comment by sonhd91** [comment]
> Please check #560. It seems an obvious and important fix.

Thanks @StefanRijnhart, I will ported this fix to this PR

**Comment by sonhd91** [comment]
> Please check #560. It seems an obvious and important fix.

Done, please check again
Since #560 base on #438 so include #438 into this port

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

@nagybal do you have a final test verdict (on the import, not on the reconciliation)?

**Comment by nagybal** [comment]
> Thanks!
> 
> @nagybal do you have a final test verdict (on the import, not on the reconciliation)?

Importing the camt file seems to be OK. BUT if I try to create a Bank kind of Journal or configure an existing one, I get the below error. If I deactivate the account_statement_import_camt the journal creates just fine.

```
UncaughtPromiseError > OwlError
Uncaught Promise > Got duplicate key in t-foreach: file_import

OwlError: Got duplicate key in t-foreach: file_import
    OwlError@
    template@
    template@[native code]
    _render@http://[ip_address]:8069/web/assets/199-4f65eb8/web.assets_common.min.js:1370:104
    render@http://[ip_address]:8069/web/assets/199-4f65eb8/web.assets_common.min.js:1369:13
    @http://[ip_address]:8069/web/assets/199-4f65eb8/web.assets_common.min.js:1448:53
    asyncFunctionResume@[native code]
    @[native code]
    promiseReactionJobWithoutPromise@[native code]

```

**Comment by nagybal** [comment]
> > Thanks!
> > @nagybal do you have a final test verdict (on the import, not on the reconciliation)?
> 
> Importing the camt file seems to be OK. BUT if I try to create a Bank kind of Journal or configure an existing one, I get the below error. If I deactivate the account_statement_import_camt the journal creates just fine.
> 
> ```
> UncaughtPromiseError > OwlError
> Uncaught Promise > Got duplicate key in t-foreach: file_import
> 
> OwlError: Got duplicate key in t-foreach: file_import
>     OwlError@
>     template@
>     template@[native code]
>     _render@http://[ip_address]:8069/web/assets/199-4f65eb8/web.assets_common.min.js:1370:104
>     render@http://[ip_address]:8069/web/assets/199-4f65eb8/web.assets_common.min.js:1369:13
>     @http://[ip_address]:8069/web/assets/199-4f65eb8/web.assets_common.min.js:1448:53
>     asyncFunctionResume@[native code]
>     @[native code]
>     promiseReactionJobWithoutPromise@[native code]
> ```

Did further troubleshooting. The account_statement_import_camt module is working without issues if I disable the account_statement_import_file_reconcile_oca. These two are still in conflict somehow!

**Comment by nagybal** [comment]
I am not sure. Is this the right topic to post the bugs to?

The imported statement is missing the partner name field. The .cam file contains it.

Screenshot 2023-05-02 at 1 00 36
Screenshot 2023-05-02 at 0 59 40

@StefanRijnhart can You confirm this?

**Comment by sonhd91** [comment]
> 
I re-tested the code on my local machine and it seems to be working correctly. I wonder what is `account_statement_import_file_reconcile_oca` has been disabled? Is that a module ?

**Comment by nagybal** [comment]
I can confirm. On the fresh install, the  account_statement_import_camt  works fine along with the account_statement_import_file_reconcile_oca

Probably an other add-on messed up my database. I had base_accounting_kit installed for short time as well. It is developed by a different team (Cybrosys).

Please proceed with the roll because I was unable to reproduce the error.

Were You able to import a camt file? Do You see the contact names after the import?

**Review by astirpe — APPROVED** [review]
Code review only (I didn't test it)

**Comment by wytzejan** [comment]
It seems that all issues are resolved. Can this one be merged? I'd like to use with the reconciliation module in production.

**Pull request merged**
