### PR TITLE
[10.0] Better parse camt groupped transactions

### PR DESCRIPTION
**Pull request by ecino**
With this change the groupped transactions that can be found in CAMT statements are better handled : this is the same changes made by @lbeopennet for version 9.0, I copy here his description:

This is primarily an addition to the camt parser to be able to handle these cases where multiple NtryDtls/TxDtls are used to represent different banking lines grouped in one Ntry. Previously the module would drop all TxDtls nodes but the first, and use it to complement the information in Ntry.

I also added exhaustive unit tests on the parser using the data file from Therp BV, and also a new one Open Net Sarl is donating. This serves to document that the changes have probably not broken anything for statements from banks that issue one Ntry per transaction, but adds support for those of some banks in Switzerland that do it this way.

### CODE REVIEW

**Comment by ecino** [comment]
Tests are now passing, is someone willing to review this?

**Comment by eLBati** [comment]
@ecino 
> This branch has conflicts that must be resolved
to resolve conflicts before continuing.
Conflicting files
account_bank_statement_import_camt/camt.py

Please check

**Comment by ecino** [comment]
Conflicts are fixed.

**Comment by ecino** [comment]
These changes are already in branch 9.0. Can someone review this PR?

**Review by eLBati — APPROVED** [review]
tested

**Review by melroy89 — APPROVED** [review]
Looks good.

**Comment by ecino** [comment]
Can we merge?

**Pull request merged**
