### PR TITLE
Fill 'ref' with 'note' when 'ref' is empty

### PR DESCRIPTION
**Pull request by nzaterrence**

### CODE REVIEW

**Comment by thomaspaulb** [comment]
Solves #138

**Comment by thomaspaulb** [comment]
@astirpe A question, [here](https://github.com/OCA/bank-statement-import/issues/138) you claim that since your swap of name and note, 'ref' is always filled. But what is the basis for this? If 'name' is filled, couldn't 'ref' still be empty?

**Comment by astirpe** [comment]
@thomaspaulb We didn't experience any case of 'ref' being empty, but if you encountered such issue, for me is a +1 to merge this PR

**Comment by astirpe** [comment]
Superseded by https://github.com/OCA/bank-statement-import/pull/178

**Comment by thomaspaulb** [comment]
@nzaterrence Can you close

**Pull request closed without merging**
