### PR TITLE
[ADD] [11.0] account_bank_statement_import_mt940_pl_raiffeisen

### PR DESCRIPTION
**Pull request by nedaszilinskas**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This should be in the corresponding localization repository, not here.

**Comment by nedaszilinskas** [comment]
I don't understand. Where is corresponding localization repository? How its different from account_bank_statement_import_mt940_nl_ing and account_bank_statement_import_mt940_nl_rabo modules in branch 10.0?

**Comment by pedrobaeza** [comment]
That's because they weren't moved. I assume this is for poland, so OCA/l10n-poland should be requested.

**Comment by nedaszilinskas** [comment]
Understood. How (or who) do I request OCA/l10n-poland to be created?

**Comment by nedaszilinskas** [comment]
@pedrobaeza how (or who) do I request OCA/l10n-poland to be created?

**Comment by pedrobaeza** [comment]
Please send an email to contribute@odoo-community.org

**Comment by okuryan** [comment]
I have sent request to create this repo

**Comment by astirpe** [comment]
@pedrobaeza we already discussed about which repository should be adopted: https://github.com/OCA/bank-statement-import/pull/95
This repository (bank-statement-import) is correct for this module. Moving the module to a localization repository is not required IMO.

**Comment by pedrobaeza** [comment]
Again this is something specific of the country. It shouldn't be here. The other time you argue it can be for other countries, and I don't continue with the debate for avoiding flames, but my points are still totally valid.

**Comment by nedaszilinskas** [comment]
@pedrobaeza @astirpe , kindly, so what is the final call on this?

**Comment by pedrobaeza** [comment]
I said my preference, but I don't want to block.

**Comment by feketemihai** [comment]
@astirpe @okuryan @nedaszilinskas @pedrobaeza  We already had this problem with romania and Croatia localisation, and the modules were moved into localisation, even it was banking, currency updates... So I think we should keep the same approach. So I vote for moving to localisation just like @pedrobaeza .

**Pull request closed without merging**
