### PR TITLE
[16.0][FIX] account_statement_import_online: use model_create_multi

### PR DESCRIPTION
**Pull request by StefanRijnhart**

### CODE REVIEW

**Review by alexey-pelykh — APPROVED** [review]
LGTM

**Comment by alexey-pelykh** [comment]
@NL66278 please also port this to other versions

**Comment by alexey-pelykh** [comment]
@StefanRijnhart please port the fix to other versions as well

**Comment by StefanRijnhart** [comment]
@alexey-pelykh thanks for the merge! Warning is not present before 16.0 (https://github.com/odoo/odoo/pull/80824/files#diff-6b27f146b1eec6bfa1d9d1d8b12af99e9ff01323bd7cd2841cb4fc72a30afe44) and module is not ported to 17.0 yet so no porting needed I think.

**Pull request merged**
