### PR TITLE
[IMP] Add German Date Format for Paypal

### PR DESCRIPTION
**Pull request by wildi1**

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
Thanks! Merging as per approvals on the original PR.

/ocabot merge minor

**Comment by StefanRijnhart** [comment]
If you have the time, could you file a port to 12.0 for this PR?

**Comment by wildi1** [comment]
Is there a manual how to do this 100% correctly, that it will be OCA conform? :)

**Comment by StefanRijnhart** [comment]
Shouldn't be a problem! Just use `git cherry-pick` of your own commit onto the new target branch.

**Pull request merged**
