### PR TITLE
[16.0][MIG] account_statement_import_camt54: Migrate to version 16.0

### PR DESCRIPTION
**Pull request by sonhd91**
Depended on :
* https://github.com/OCA/account-reconcile/pull/514/
* https://github.com/OCA/bank-statement-import/pull/550/
* https://github.com/OCA/bank-statement-import/pull/575/
* https://github.com/OCA/bank-statement-import/pull/556/

### CODE REVIEW

**Review by yankinmax — APPROVED** [review]

**Review by santostelmo — APPROVED** [review]

**Comment by StephaneMangin** [comment]
cc @sonhd91 You have to change one of your dependency from https://github.com/OCA/bank-statement-import/pull/535 to https://github.com/OCA/bank-statement-import/pull/575 and this PR will be good

**Comment by StephaneMangin** [comment]
There are another PRs that need to be updated.

**Comment by sonhd91** [comment]
> There are another PRs that need to be updated.

Hi @StephaneMangin, I udpated the PR, please check again

**Comment by sonhd91** [comment]
> There are another PRs that need to be updated.

Hi @StephaneMangin, I updated the PR, please check again

**Comment by StephaneMangin** [comment]
cc @sonhd91 Once the dependency (waiting for it's own dependency to be merged) of you PR is merged you could update this one. Please follow up

**Comment by StephaneMangin** [comment]
cc @sonhd91 Any update about this PR ?

**Comment by sonhd91** [comment]
> cc @sonhd91 Any update about this PR ?

Yeah, I'm still waiting for `account_statement_import_camt` migrate PR to be merged

**Comment by gurneyalex** [comment]
@sonhd91 hello, all the dependency PRs are merged, can you drop the test-requirements commit https://github.com/OCA/bank-statement-import/pull/562/commits/f8e388b6eb33f91fdc798912f676ee0dcc32c66c so we can merge this one?

**Comment by sonhd91** [comment]
> @sonhd91 hello, all the dependency PRs are merged, can you drop the test-requirements commit [f8e388b](https://github.com/OCA/bank-statement-import/commit/f8e388b6eb33f91fdc798912f676ee0dcc32c66c) so we can merge this one?

Done, please check again

**Pull request merged**
