### PR TITLE
[14.0][MIG] account_statement_import_online_wise : Migration to 14.0

### PR DESCRIPTION
**Pull request by ecino**

### CODE REVIEW

**Comment by ecino** [comment]
@alexey-pelykh Willing to review?

**Review by alexey-pelykh — APPROVED** [review]
Code LGTM

**Comment by alexey-pelykh** [comment]
@ecino could you please rebase and push? So that Runboat kicks in

**Comment by alexey-pelykh** [comment]
The pre-commit would prevent the automatic merging, otherwise looks good

**Comment by ecino** [comment]
@alexey-pelykh Weirdly, the pre-commit doesn't report any issues on my local environment. Not sure what the error is about.

**Comment by bosd** [comment]
Can you please rebase? Maybe that will fix pre-commit

**Comment by ecino** [comment]
@bosd unfortunately not.

**Comment by bosd** [comment]
I tried to fix in #658.
But it is not enough.

we need manual intervention on po files.
As mentioned in #633.
I don't know how to do that.

Let's hope a maintainer jumps in here.

**Comment by ecino** [comment]
Are we good to merge now? Lights are green.

**Comment by alexey-pelykh** [comment]
@ecino not exactly, merge needs to be done as rebase yet bot should take care of that - if that works I'll merge

**Comment by alexey-pelykh** [comment]
@ecino please do a manual rebase

**Comment by ecino** [comment]
@alexey-pelykh Rebase done

**Pull request merged**
