### PR TITLE
[17.0][MIG] account_statement_import_online_ponto: Migration to 17.0

### PR DESCRIPTION
**Pull request by ChristianTessera**
Standard migration to 17.0

### CODE REVIEW

**Review by victoralmau — APPROVED** [review]
Code review OK.

Please, change tiitle to _[17.0][MIG] account_statement_import_online_ponto: Migration to 17.0_ 

Could you squash administrative commits?

**Review by christian-ramos-tecnativa — APPROVED** [review]
LGTM

**Comment by jelenapoblet** [comment]
This is the only suggestion after testing
captura-myponto
I would use Client ID and Client Secret instead of Login and Secret Key
Tested and pulled the statements without problems

**Pull request merged**
