### PR TITLE
[15.0][mig] account_statement_import_online_paypal

### PR DESCRIPTION
**Pull request by ikapasi-initos**

### CODE REVIEW

**Comment by dsolanki-initos** [comment]
@alexey-pelykh I have committed the code but it is still showing me a stale label so can you please remove the stale label?

**Comment by alexey-pelykh** [comment]
@dsolanki-initos the precommit still fails, you need to address that

**Comment by jans23** [comment]
This module seems to be inconsequently renamed from account_bank_statement_import_online_paypal to account_statement_import_online_paypal. Why is this?

**Comment by dsolanki-initos** [comment]
> This module seems to be inconsequently renamed from account_bank_statement_import_online_paypal to account_statement_import_online_paypal. Why is this?

@jans23 As it is an OCA module from v14.0 it is renamed to "account_statement_import_online_paypal" and we have to go with a new name.

**Review by dreispt — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
Superseded by https://github.com/OCA/bank-statement-import/pull/571 to include v14 commits and adapt it up to today v15 repo.

**Review by MiquelRForgeFlow — CHANGES_REQUESTED** [review]
So this should be closed. Please review the other PR.

**Comment by OSevangelist** [comment]
This PR is closed upon request of @MiquelRForgeFlow as it has been superseeded by https://github.com/OCA/bank-statement-import/pull/571

**Pull request closed without merging**
