### PR TITLE
[13.0][FIX] account_bank_statement_import_txt_xlsx

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Superseed #405 due to stale 

CC @ForgeFlow

### CODE REVIEW

**Review by alexey-pelykh — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
@HviorForgeFlow I would assume this should be back- and forward-ported as well?

**Comment by HviorForgeFlow** [comment]
At least forward-ported to v14 where module is available, and make a reference here: https://github.com/OCA/bank-statement-import/pull/506

**Comment by alexey-pelykh** [comment]
@HviorForgeFlow would you do the honors for https://github.com/OCA/bank-statement-import/blob/12.0/account_bank_statement_import_txt_xlsx/models/account_bank_statement_import_sheet_parser.py#L314 and https://github.com/OCA/bank-statement-import/blob/14.0/account_statement_import_txt_xlsx/models/account_statement_import_sheet_parser.py#L362 ?

**Comment by alexey-pelykh** [comment]
I'll merge them as soon as PRs are ready

**Pull request merged**
