### PR TITLE
[8.0] enhancements 2016-10-20

### PR DESCRIPTION
**Pull request by NL66278**
Merge plethora of never merged improvements with latest version of 8.0 branch.

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]
Can you squash commits?

**Comment by pedrobaeza** [comment]
This is conflicting currently. Is this still relevant for an outdated version like 8.0?

**Comment by NL66278** [comment]
Note that this PR includes these:
https://github.com/OCA/bank-statement-import/pull/117
and
https://github.com/OCA/bank-statement-import/pull/78
If the above PR's were to be accepted/merged, I could rebase this one, and squash all commits for changes remaining.

**Comment by thomaspaulb** [comment]
@NL66278 It seems you also address what I am addressing here:

https://github.com/OCA/bank-statement-import/pull/146

**Comment by NL66278** [comment]
@thomaspaulb No I was addressing another issue. A confusion between a companies bank account, where the company also had a partner bank account in another company. Which would be a normal situation in any multi company database with companies that transfer money through the banks to each other.

**Comment by thomaspaulb** [comment]
@NL66278 That is what I was also addressing

**Comment by NL66278** [comment]
@thomaspaulb Then I misunderstood your code. Sorry for that.

**Pull request closed without merging**
