### PR TITLE
[16.0][MIG] account_bank_statement_import_qif > account_statement_import_qif: Migration to 16.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 16.0 (renamed to `account_statement_import_qif`)

Please @pedrobaeza and @carolinafernandez-tecnativa can you review it?

@Tecnativa TT46557

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by victoralmau** [comment]
Ping @carolinafernandez-tecnativa

**Review by carolinafernandez-tecnativa — APPROVED** [review]
Funcional review, LGTM :) Thanks!

**Pull request merged**
