### PR TITLE
[17.0][MIG] account_statement_import_base: Migration to 17.0

### PR DESCRIPTION
**Pull request by rov-adhoc**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please remember to name the PR accordingly for being found in searches. I'm going to wait to mark it for migration until you have it green.

**Comment by rov-adhoc** [comment]
Depends on:

- [614]  https://github.com/OCA/account-reconcile/pull/614

**Comment by StefanRijnhart** [comment]
I think you can get your stack of PRs (thanks!) green by adding unmerged dependencies in test-requirements.txt. This is described here: https://odoo-community.org/groups/contributors-15/contributors-175721 (I hope it is still up to date).

**Comment by StefanRijnhart** [comment]
In an attempt to restart tests after the dependent module was merged (I don't have access to the 'rerun failed tests button in the Github Actions):

/ocabot rebase

**Comment by StefanRijnhart** [comment]
@rov-adhoc My attempt to restart tests failed. Can you rebase or restart tests manually?

**Comment by rov-adhoc** [comment]
@StefanRijnhart 
done! thanks!! Best regards

**Review by StefanRijnhart — APPROVED** [review]
Thanks for the rebase! I checked the code and there is nothing to be migrated in this very simple base module indeed.

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration account_statement_import_base
/ocabot merge nobump

**Pull request merged**
