### PR TITLE
[10.0] add import helper

### PR DESCRIPTION
**Pull request by luc-demeyer**
This module adds support for local bank accounts as subset of IBAN accounts for the bank statement import.

### CODE REVIEW

**Review by alexis-via — APPROVED** [review]
This module is a good replacement for my module "account_bank_statement_import_usability". This feature is really needed.

**Comment by pedrobaeza** [comment]
Can you check Travis and runbot status?

**Comment by pedrobaeza** [comment]
I'm afraid it's still failing:
```
account_bank_statement_import_helper/wizard/account_bank_statement_import.py:34:25: E126 continuation line over-indented for hanging indent
```
and this makes other tests to fail (note the line where it fails)
```
2018-08-08 08:35:11,657 4446 ERROR openerp_test odoo.addons.account_bank_statement_import_mt940_base.tests.test_import_bank_statement: `   File "/home/travis/build/OCA/bank-statement-import/account_bank_statement_import_helper/wizard/account_bank_statement_import.py", line 26, in <lambda>
2018-08-08 08:35:11,657 4446 ERROR openerp_test odoo.addons.account_bank_statement_import_mt940_base.tests.test_import_bank_statement: `     in r.bank_account_id.sanitized_acc_number)
2018-08-08 08:35:11,657 4446 ERROR openerp_test odoo.addons.account_bank_statement_import_mt940_base.tests.test_import_bank_statement: ` TypeError: argument of type 'bool' is not iterable
```

**Comment by luc-demeyer** [comment]
The easy part is now fixed (flake8 issues).
I'll analyse & fix the failing unit test later this week.

**Comment by luc-demeyer** [comment]
Travis is finally green now.
Thanks to the use of unit tests I could identify and fix a serious bug in my PR. 

Can some have a look to the CLA warning from oca-clabot a higher in this thread ?
I have signed the oca CLA many years ago. Do we need to resign or is there an error in the toolset ?

**Comment by pedrobaeza** [comment]
The problem is that you have made an incorrect rebase/pull/merge operation, and now this PR contains a lot of commits that are not related. Please clean the branch.

**Pull request closed without merging**
