### PR TITLE
[13.0][ADD] account_bank_statement_import_file_hook

### PR DESCRIPTION
**Pull request by JaumeBforgeFlow**

### CODE REVIEW

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! 👍🏽

**Review by mariadforgeflow — APPROVED** [review]
LVGTM!

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by JordiMForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Wait, aborting. Why do you need to do such hooks? This is a very bad practice. What do you want to get?

**Comment by JaumeBforgeFlow** [comment]
@pedrobaeza, Odoo does the processing of the file in such a way that you are not able to tap into the logic, to modify it while having access to the ir.attachment record being processed. None of the functions called inside the for loop in the import_file() function are passed the attachment as a record.

Having this hook might be interesting in cases such as the one we are working with, where we want to link the resulting statement with the attachment.

**Comment by pedrobaeza** [comment]
I think you can override `_parse_file` method, that has as argument the decoded file content, and include in the returned dictionary these contents in a special key. Then override the `create` method of `account.bank.statement`, and if you find such key, pop it, call super, and then create the attachment.

**Comment by AaronHForgeFlow** [comment]
Hi, just reopening this

**Comment by AaronHForgeFlow** [comment]
sorry wrong PR

**Pull request closed without merging**
