### PR TITLE
[14.0] account_statement_import_camt - fix counterparty data

### PR DESCRIPTION
**Pull request by luc-demeyer**

### CODE REVIEW

**Comment by luc-demeyer** [comment]
this PR contains two fixes:

1) counterparty partner_name

CAMT files from german unicredit bank use <Cdtr><Pty><Nm> in stead of <Cdtr><Nm> hence I have added this use case

2) counterparty account number

Clear bug fix.

**Review by ghost — APPROVED** [review]

**Comment by nagybal** [comment]
When will be account_statement_import_camt modul published for 16.0 ?

**Review by StefanRijnhart — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please fw-port the patch to upper versions if applicable.

**Comment by luc-demeyer** [comment]
forward port to 15.0: cf. https://github.com/OCA/bank-statement-import/pull/585

**Pull request merged**
