### PR TITLE
[14.0][IMP] account_statement_import_txt_xlsx - improve columns/fields inheratibility 

### PR DESCRIPTION
**Pull request by ghost**
If you want to add new fields in the mapping, it's a bit hard since everything is done inside loops. So I split the parsing in several functions to be able to do a super in the middle of the process and be able to add new fields/columns

Example (partial one) with the improvements : 

```
def _parse_columns(self, mapping, header, columns):
        res = super()._parse_columns(mapping, header, columns)
        columns["transaction_date_column"] = (
            header.index(mapping.transaction_date_column) if mapping.transaction_date_column else None
        )
        columns["value_date_column"] = (
            header.index(mapping.value_date_column) if mapping.value_date_column else None
        )
        return res
```

### CODE REVIEW

**Comment by Saran440** [comment]
@jdidderen-be Could you check test script error, please?

and I think this PR similar https://github.com/OCA/bank-statement-import/pull/476
we need hook some function for add something.

May be you can check and combine to yourr PR?
Thank you

**Comment by ghost** [comment]
@Saran440 The error is solved. It seems that the issues came from another module and that it has been resolved in the meantime.

I looked at the PR #476 and I think we achieve the same thing. Just not in the same way. For example, in our case, we have some custom fields and based on this PR, I made this inherit:

```python
class AccountStatementImportSheetParser(models.TransientModel):
    _inherit = "account.statement.import.sheet.parser"

    def _parse_columns(self, mapping, header, columns):
        res = super()._parse_columns(mapping, header, columns)
        columns["transaction_date_column"] = (
            header.index(mapping.transaction_date_column) if mapping.transaction_date_column else None
        )
        columns["value_date_column"] = (
            header.index(mapping.value_date_column) if mapping.value_date_column else None
        )
        return res

    def _parse_row(self, mapping, currency_code, values, columns):
        line = super()._parse_row(mapping, currency_code, values, columns)
        value_date = (
            values[columns["value_date_column"]]
            if columns["value_date_column"] is not None
            else None
        )
        transaction_date = (
            values[columns["transaction_date_column"]]
            if columns["transaction_date_column"] is not None
            else None
        )
        if value_date and isinstance(value_date, str):
            value_date = datetime.strptime(value_date, mapping.timestamp_format)
        else:
            value_date = None
        if transaction_date and isinstance(transaction_date, str):
            transaction_date = datetime.strptime(transaction_date, mapping.timestamp_format)
        else:
            transaction_date = None
        if value_date is not None:
            line["value_date"] = value_date
        if transaction_date is not None:
            line["transaction_date"] = transaction_date
        return line

    @api.model
    def _convert_line_to_transactions(self, line):  # noqa: C901
        transaction = super()._convert_line_to_transactions(line)
        if line.get("transaction_date", False):
            transaction[0]["transaction_date"] = line.get("transaction_date")
        if line.get("value_date", False):
            transaction[0]["val_date"] = line.get("value_date")
        return transaction
```

Based on that example, do you think it's enough for you or something else should be done ?

**Comment by Saran440** [comment]
@ps-tubtim Please, Can you check this pr is enough for hook function?

**Comment by ps-tubtim** [comment]
> @ps-tubtim Please, Can you check this pr is enough for hook function?

@Saran440 This PR is ok with me. It's enough for hook function.

**Review by ps-tubtim — APPROVED** [review]

**Review by Saran440 — APPROVED** [review]
Functional Test :+1

**Comment by Saran440** [comment]
@OCA/banking-maintainers This PR is ready to merge someone please help.

**Comment by JordiBForgeFlow** [comment]
@jdidderen-noviat seems that there are some conflicts. Can you try to rebase and check?

**Comment by ghost** [comment]
@JordiBForgeFlow Sorry for the late reply. The rebase is done and the conflict is solved now.

**Pull request merged**
