### PR TITLE
New backport from odoo/master

### PR DESCRIPTION
**Pull request by alexis-via**
This backport adds some new features:
- auto-detect account.journal for OFX files (I had to make a light change in the code to make it work in real life)
- block when trying to import lines that were already imported in another statement

Note that I disabled the auto-creation of account.journal, because I find it very hazardous.

This new backport also fixes bug #5 : no more manual creation of temporary file.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please check PEP8?

**Comment by NL66278** [comment]
Hello Alexis,

I was also already rewriting the migrated camt parser to the new functionality. So thanks for this PR.

One question: what danger do you see in automatically creating journals for bank-accounts? Already in 7.0 and 8.0 and maybe before, when creating a company bank account, a journal was automatically created. So why not during the import?

**Comment by alexis-via** [comment]
@NL66278 
I fear that, if you import a wrong OFX file by mistake, it will create a new bank journal, etc... Companies don't open new bank accounts very often and, when you do it, they expect to have some configuration work to do in OpenERP. I fear that this feature will lead more ofter to the creation of wrong bank journals that will need to be deleted than to the creation of real bank journals. And, even with the auto-creation of the bank journal, the accountant will have to manually finish the config of the bank journal in the form view of the bank journal.

What do you think ?

**Comment by sbidoul** [comment]
@pedrobaeza regarding pep8, since this is a backport, I prefer adding noqa so it remains easy to compare with upstream.

@alexis-via @NL66278 I've not read the code in details but after reading your comments, I also think auto-creating journals or bank accounts for the user's company is hazardous. This is especially true in a multi-company context where users can easily mix bank statements from the available companies: that must not result in creating journals in the wrong company.

**Comment by alexis-via** [comment]
@NL66278 @sbidoul 
As some people may be interested by the "auto-create journal" feature (even if I think it's not a good idea and, as Stéphane said, it is particularly dangerous for multi-company accountants who won't be blocked when they import an OFX file in the wrong company), I decided to re-activate the code, but you must have a special key in the context to go in that code (and this special key in the context is not set by these modules, you would have to set it via a custom module).

**Comment by alexis-via** [comment]
I just noticed that the method _detect_partner() has been dropped in this version ; it seems the "replacement" is the method _complete_stmts_vals() (but it's just a very quick guess).

**Comment by NL66278** [comment]
:+1:  Would be nice to put in the #noqa's though. I will rebase my own pull request (adding camt parser and a few more things) on this code.

**Comment by NL66278** [comment]
Two more things:
- maybe needed to put creation of a journal in the demo data, because autocreation has been disabled in the code.
- In the original code the expected test data is adapted to the wrong computations of start/end balance (which somehow defeats the purpose of automatic testing). The test should assume an end-balance of 2156,56 (that is now the amount of the start balance), and it should assume a start balance of 2516,56, because the transactions add up to minus 360.

**Comment by alexis-via** [comment]
I think we are ready to merge this now. I plan to start deploying it now that I ported the CFONB import (French text files) to this new framework.
:+1:

**Comment by pedrobaeza** [comment]
There are still pending Travis issues.

**Comment by NL66278** [comment]
It seems the framework is using a completely different version of _prepare_bank_account from the wizard wizard.multi.charts.accounts than present in the 8.0 addons.

**Comment by NL66278** [comment]
I would suggest to disable the journal (and company bank account) creation completely, and create the bank account and journal needed for test from demo data.

**Comment by alexis-via** [comment]
Just a small note to tell you that I now run this version in production at a customer site. It may not be perfect, it may not please my friend Travis, but it's not as buggy as the current official branch with the huge bug on manual temporary file creation :)

**Comment by NL66278** [comment]
@alexis-via Just to say I am very glad with the work you have done to backport and improve the import framework. And you were very right with your remarks on the problems with automatic creation of journals. That part is not working anyway - because of the differences in the account module betwee 8.0 and master -, therefore my proposal to just take it out and warn customers if configuration has not been done.

**Comment by NL66278** [comment]
@alexis-via  Please have a look at the PR I created for your fork/branch.

**Comment by NL66278** [comment]
The remaining failed pylint check (tests are going OK now) seem to be due to an internal travis problem. Ik have no idea how or why, but for some reason my Pull request seems to be tested with a total different version of travis:

I took a diff of the log files:

\- Alexis Pull Request

\+ My pull request
Just showing the lines with the travis version:

-23bb455 https://github.com/travis-ci/travis-cookbooks/tree/23bb455

+4f2272c https://github.com/travis-ci/travis-cookbooks/tree/4f2272c

As I said, I have no idea why this difference occurs. Let alone how to solve it.

**Comment by alexis-via** [comment]
I deployed this new PR in production on v8 with a second customer, and we successfully imported an OFX file from a french bank.

**Comment by NL66278** [comment]
:+1:  Once again. Code review and tested. Can somebody with the power to merge act on this?

**Comment by pedrobaeza** [comment]
I'm testing just right now, and when I finish it, I'll give my positive review and merge.

**Comment by pedrobaeza** [comment]
All is correct, so I proceed to merge.

Thanks for backporting this, Alexis.

**Pull request merged**
