### PR TITLE
[10.0][MIG] Allow camt parser inheritance

### PR DESCRIPTION
**Pull request by ecino**
Modify camt parser to be an Odoo AbstractModel instead of a pure python object.
This allows inheritance in sub-modules to customize the parser and is needed in Switzerland to extend the functionnalities of the parser.

This is already present in version 9 and should be done as well in version 10.

### CODE REVIEW

**Comment by ecino** [comment]
I think this should be merged before camt parser will be ported to v11.

**Comment by ecino** [comment]
Can someone review this please?

**Review by hbrunn — APPROVED** [review]

**Review by astirpe — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please change module version number

**Comment by ecino** [comment]
Changed version of module

**Pull request merged**
