### PR TITLE
[17.0][MIG] account_statement_import_online: Migration to 17.0

### PR DESCRIPTION
**Pull request by carolinafernandez-tecnativa**
- Standard migration to v17.
- Add test-requirements.txt odoo_test_helper to avoid getting error in test that odoo_test_helper not found

@Tecnativa
TT49855
@pedrobaeza @pilarvargas-tecnativa

### CODE REVIEW

**Comment by carolinafernandez-tecnativa** [comment]
ping @pedrobaeza @pilarvargas-tecnativa

**Comment by pilarvargas-tecnativa** [comment]
When I try to create a provider I get the following error:

```
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1764, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1791, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 1995, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 741, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/web/models/models.py", line 1080, in onchange
    snapshot1 = RecordSnapshot(record, fields_spec)
  File "/opt/odoo/addons/web/models/models.py", line 1167, in __init__
    self.fetch(name)
  File "/opt/odoo/addons/web/models/models.py", line 1182, in fetch
    self[field_name] = self.record[field_name]
  File "/opt/odoo/odoo/models.py", line 6636, in __getitem__
    return self._fields[key].__get__(self, self.env.registry[self._name])
  File "/opt/odoo/odoo/fields.py", line 1207, in __get__
    self.compute_value(recs)
  File "/opt/odoo/odoo/fields.py", line 1389, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 424, in _compute_field_value
    return super()._compute_field_value(field)
  File "/opt/odoo/odoo/models.py", line 4880, in _compute_field_value
    fields.determine(field.compute, self)
  File "/opt/odoo/odoo/fields.py", line 102, in determine
    return needle(*args)
  File "/opt/odoo/odoo/models.py", line 1663, in _compute_display_name
    record.display_name = convert(record[self._rec_name], record)
  File "/opt/odoo/odoo/models.py", line 6636, in __getitem__
    return self._fields[key].__get__(self, self.env.registry[self._name])
  File "/opt/odoo/odoo/fields.py", line 1152, in __get__
    self.recompute(record)
  File "/opt/odoo/odoo/fields.py", line 1367, in recompute
    apply_except_missing(self.compute_value, recs)
  File "/opt/odoo/odoo/fields.py", line 1340, in apply_except_missing
    func(records)
  File "/opt/odoo/odoo/fields.py", line 1389, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 424, in _compute_field_value
    return super()._compute_field_value(field)
  File "/opt/odoo/odoo/models.py", line 4880, in _compute_field_value
    fields.determine(field.compute, self)
  File "/opt/odoo/odoo/fields.py", line 102, in determine
    return needle(*args)
  File "/mnt/data/odoo-addons-dir/account_statement_import_online/models/online_bank_statement_provider.py", line 167, in _compute_name
    provider.name = " ".join([provider.journal_id.name, provider.service])
TypeError: sequence item 0: expected str instance, bool found

The above server error caused the following client error:
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    Error: An error occured in the owl lifecycle (see this Error's "cause" property)
        at handleError (http://oca-bank-statement-import-17-0-pr706-d3cc92dd674f.runboat.odoo-community.org/web/assets/b8308fe/web.assets_web.min.js:916:101)
        at App.handleError (http://oca-bank-statement-import-17-0-pr706-d3cc92dd674f.runboat.odoo-community.org/web/assets/b8308fe/web.assets_web.min.js:1543:29)
        at ComponentNode.initiateRender (http://oca-bank-statement-import-17-0-pr706-d3cc92dd674f.runboat.odoo-community.org/web/assets/b8308fe/web.assets_web.min.js:1006:19)

Caused by: RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (http://oca-bank-statement-import-17-0-pr706-d3cc92dd674f.runboat.odoo-community.org/web/assets/b8308fe/web.assets_web.min.js:2884:163)
        at XMLHttpRequest.<anonymous> (http://oca-bank-statement-import-17-0-pr706-d3cc92dd674f.runboat.odoo-community.org/web/assets/b8308fe/web.assets_web.min.js:2888:13)

**Comment by carolinafernandez-tecnativa** [comment]
> When I try to create a provider I get the following error:
> 
> ```
> Traceback (most recent call last):
>   File "/opt/odoo/odoo/http.py", line 1764, in _serve_db
>     return service_model.retrying(self._serve_ir_http, self.env)
>   File "/opt/odoo/odoo/service/model.py", line 133, in retrying
>     result = func()
>   File "/opt/odoo/odoo/http.py", line 1791, in _serve_ir_http
>     response = self.dispatcher.dispatch(rule.endpoint, args)
>   File "/opt/odoo/odoo/http.py", line 1995, in dispatch
>     result = self.request.registry['ir.http']._dispatch(endpoint)
>   File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
>     result = endpoint(**request.params)
>   File "/opt/odoo/odoo/http.py", line 741, in route_wrapper
>     result = endpoint(self, *args, **params_ok)
>   File "/opt/odoo/addons/web/controllers/dataset.py", line 24, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "/opt/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/opt/odoo/odoo/api.py", line 468, in call_kw
>     result = _call_kw_multi(method, model, args, kwargs)
>   File "/opt/odoo/odoo/api.py", line 453, in _call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "/opt/odoo/addons/web/models/models.py", line 1080, in onchange
>     snapshot1 = RecordSnapshot(record, fields_spec)
>   File "/opt/odoo/addons/web/models/models.py", line 1167, in __init__
>     self.fetch(name)
>   File "/opt/odoo/addons/web/models/models.py", line 1182, in fetch
>     self[field_name] = self.record[field_name]
>   File "/opt/odoo/odoo/models.py", line 6636, in __getitem__
>     return self._fields[key].__get__(self, self.env.registry[self._name])
>   File "/opt/odoo/odoo/fields.py", line 1207, in __get__
>     self.compute_value(recs)
>   File "/opt/odoo/odoo/fields.py", line 1389, in compute_value
>     records._compute_field_value(self)
>   File "/opt/odoo/addons/mail/models/mail_thread.py", line 424, in _compute_field_value
>     return super()._compute_field_value(field)
>   File "/opt/odoo/odoo/models.py", line 4880, in _compute_field_value
>     fields.determine(field.compute, self)
>   File "/opt/odoo/odoo/fields.py", line 102, in determine
>     return needle(*args)
>   File "/opt/odoo/odoo/models.py", line 1663, in _compute_display_name
>     record.display_name = convert(record[self._rec_name], record)
>   File "/opt/odoo/odoo/models.py", line 6636, in __getitem__
>     return self._fields[key].__get__(self, self.env.registry[self._name])
>   File "/opt/odoo/odoo/fields.py", line 1152, in __get__
>     self.recompute(record)
>   File "/opt/odoo/odoo/fields.py", line 1367, in recompute
>     apply_except_missing(self.compute_value, recs)
>   File "/opt/odoo/odoo/fields.py", line 1340, in apply_except_missing
>     func(records)
>   File "/opt/odoo/odoo/fields.py", line 1389, in compute_value
>     records._compute_field_value(self)
>   File "/opt/odoo/addons/mail/models/mail_thread.py", line 424, in _compute_field_value
>     return super()._compute_field_value(field)
>   File "/opt/odoo/odoo/models.py", line 4880, in _compute_field_value
>     fields.determine(field.compute, self)
>   File "/opt/odoo/odoo/fields.py", line 102, in determine
>     return needle(*args)
>   File "/mnt/data/odoo-addons-dir/account_statement_import_online/models/online_bank_statement_provider.py", line 167, in _compute_name
>     provider.name = " ".join([provider.journal_id.name, provider.service])
> TypeError: sequence item 0: expected str instance, bool found
> 
> The above server error caused the following client error:
> OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
>     Error: An error occured in the owl lifecycle (see this Error's "cause" property)
>         at handleError (http://oca-bank-statement-import-17-0-pr706-d3cc92dd674f.runboat.odoo-community.org/web/assets/b8308fe/web.assets_web.min.js:916:101)
>         at App.handleError (http://oca-bank-statement-import-17-0-pr706-d3cc92dd674f.runboat.odoo-community.org/web/assets/b8308fe/web.assets_web.min.js:1543:29)
>         at ComponentNode.initiateRender (http://oca-bank-statement-import-17-0-pr706-d3cc92dd674f.runboat.odoo-community.org/web/assets/b8308fe/web.assets_web.min.js:1006:19)
> 
> Caused by: RPC_ERROR: Odoo Server Error
>     RPC_ERROR
>         at makeErrorFromResponse (http://oca-bank-statement-import-17-0-pr706-d3cc92dd674f.runboat.odoo-community.org/web/assets/b8308fe/web.assets_web.min.js:2884:163)
>         at XMLHttpRequest.<anonymous> (http://oca-bank-statement-import-17-0-pr706-d3cc92dd674f.runboat.odoo-community.org/web/assets/b8308fe/web.assets_web.min.js:2888:13)
> ```

Fixed it, could you please try again? :)

**Review by pilarvargas-tecnativa — APPROVED** [review]

**Comment by carolinafernandez-tecnativa** [comment]
ping @pedrobaeza

**Comment by pedrobaeza** [comment]
On both v16 and v17, once you select one online provider (there's no provider in this PR, but you can check on v16), there's no way to configure the parameters of this provider. Can you please check it and fix it in both versions, starting with v16?

**Comment by carolinafernandez-tecnativa** [comment]
> On both v16 and v17, once you select one online provider (there's no provider in this PR, but you can check on v16), there's no way to configure the parameters of this provider. Can you please check it and fix it in both versions, starting with v16?

Fixed added in v16 https://github.com/OCA/bank-statement-import/pull/710

Once approved, i will forward it.

**Comment by carolinafernandez-tecnativa** [comment]
> > On both v16 and v17, once you select one online provider (there's no provider in this PR, but you can check on v16), there's no way to configure the parameters of this provider. Can you please check it and fix it in both versions, starting with v16?
> 
> Fixed added in v16 #710
> 
> Once approved, i will forward it.

Fw #710 done @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
