### PR TITLE
11.0 mig account bank statement import ofx

### PR DESCRIPTION
**Pull request by njeudy**

### CODE REVIEW

**Comment by njeudy** [comment]
Will add #136 patch if it it merged in V10

**Comment by pedrobaeza** [comment]
@njeudy please integrate #136 here for continuing with the migration.

**Comment by njeudy** [comment]
@pedrobaeza ok wil do it end of week

**Comment by njeudy** [comment]
@pedrobaeza ok done I include #136 in my commit

**Review by pedrobaeza — APPROVED** [review]

**Comment by njeudy** [comment]
@pedrobaeza could we merge ?

**Pull request merged**
