### PR TITLE
[8.0] account_bank_statement_import_camt: allow camt054 to be parsed

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Review by NL66278 — APPROVED** [review]
👍 LGTM. And already approved on 9.0.

**Comment by pedrobaeza** [comment]
Please change module version number

**Comment by eLBati** [comment]
@pedrobaeza done

**Review by astirpe — APPROVED** [review]

**Comment by alexis-via** [comment]
Same remark : please update the error msg on line 228 of camt.py

**Pull request closed without merging**
