### PR TITLE
[15.0][MIG]account_statement_import_online

### PR DESCRIPTION
**Pull request by manuelregidor**
Standard migration.

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Review by rafaelbn — APPROVED** [review]
Thanks 👍

**Review by HaraldPanten — APPROVED** [review]
Tested in production environment and it's working well. I'll merge this one tomorrow, as well. --> https://github.com/OCA/bank-statement-import/pull/463

**Pull request merged**
