### PR TITLE
account_bank_statement_import_camt: parse unique_import_id; properly …

### PR DESCRIPTION
**Pull request by andrius-preimantas**
…select statement date; remove unexpected values like execution_date, value_date, etc. - standard Odoo does not expect those

### CODE REVIEW

**Comment by ghost** [comment]
I noticed that CreDtTm is a datetime and that its value goes straight into `statement['date']`, this is a problem because it's formatted like `2014-01-06T16:20:26.673Z`, and it seems that Odoo simply ignores it on create. By applying [this patch](https://github.com/lbeopennet/bank-statement-import/commit/00c4e0c7f300e3c8dcbdd54bbf26d2f508f07cc1) I got the right date on the statement in production.

Note that said production is in 9.0 and that I'm rebasing your branch onto 9.0. Also see [the whole branch](https://github.com/lbeopennet/bank-statement-import/commits/10.0_103-fix-datetime) to see what effect the changes have in the unit tests. (These enhanced unit tests are being PRd inside #102.) Other than that LGTM. We really should not be injecting names that don't match any database field.

**Comment by andrius-preimantas** [comment]
@lbeopennet , it's been a while :-) But I made changes according to your feedback. However I was not comfortable parsing `2014-01-06T16:20:26.673Z` as a string. I hope that's ok with you. Let me know if any further changes are needed.

**Comment by ghost** [comment]
@andrius-preimantas Hi. You're right, it's probably smarter that way. I ran [similar technical tests](https://travis-ci.org/lbeopennet/ci-staging/builds/283291400) to what I mentionned on Apr 20th and the date comes out as expected. I haven't done any functional tests. The date was the sole objection that I had so I'm approving this PR.

**Review by ghost — APPROVED** [review]

**Comment by andrius-preimantas** [comment]
@lbeopennet , thanks. What can I do to make this one merge faster?

**Comment by alexis-via** [comment]
When I try your PR with an up-to-date Odoo v10, I get this crash:
```
2018-02-20 08:19:30,617 4500 ERROR o0_test2 odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/alexis/new_boite/dev/odoo0/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/alexis/new_boite/dev/odoo0/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/alexis/new_boite/dev/odoo0/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo0/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo0/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/alexis/new_boite/dev/odoo0/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/alexis/new_boite/dev/odoo0/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/alexis/new_boite/dev/odoo0/addons/web/controllers/main.py", line 894, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/alexis/new_boite/dev/odoo0/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/alexis/new_boite/dev/odoo0/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/home/alexis/new_boite/dev/odoo0/odoo/api.py", line 670, in call_kw_model
    recs = self.with_context(context or {})
  File "/home/alexis/new_boite/dev/odoo0/odoo/models.py", line 4890, in with_context
    context = dict(args[0] if args else self._context, **kwargs)
TypeError: cannot convert dictionary update sequence element #0 to a sequence
```

**Pull request closed without merging**
