### PR TITLE
[13.0][UPD] account_bank_statement_import_online_paypal: new paypal event_code, T0403

### PR DESCRIPTION
**Pull request by ntsirintanis**
Update `EVENT_DESCRIPTION` with additional key, `T0403`

[link](https://developer.paypal.com/docs/reports/reference/tcodes/)

### CODE REVIEW

**Comment by ntsirintanis** [comment]
@NL66278 @lfreeke

**Review by lfreeke — APPROVED** [review]

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Review by alexey-pelykh — APPROVED** [review]

**Review by alexey-pelykh — APPROVED** [review]

**Comment by thomaspaulb** [comment]
@OCA/banking-maintainers

**Pull request merged**
