### PR TITLE
[FIX] have one list of notifications

### PR DESCRIPTION
**Pull request by hbrunn**
With the current code, you end up with a list of lists, I don't think that's what we want

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Does this happen also in upstream v9?

For this, :+1:

**Comment by hbrunn** [comment]
@pedrobaeza no, this happens in the indirection `_import_file` which is specific to our code

**Comment by pedrobaeza** [comment]
OK, thanks for the info.

**Comment by sbidoul** [comment]
:+1: (code review, no test)

**Comment by lmignon** [comment]
:+1:  (code review, no test)

**Pull request merged**
