### PR TITLE
[13.0][REBRAND] account_bank_statement_import_paypal

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please don't self-merge without even any time to comment anything. The new copyright shouldn't be put in each file, as you haven't touched them.

**Comment by alexey-pelykh** [comment]
@pedrobaeza that's not exactly true, I did touch them, copyright from Brainbean Apps migrated to CorporateHub

**Comment by pedrobaeza** [comment]
hahaha, you have touched them to add the copyright. That's not touching it. I changed also my branding, and changed the author in manifest, but not add in the new year a copyright in all files. When I changed something in that files, then I add for the year I changed it the new line.

**Pull request merged**
