### PR TITLE
8.0 camt statement

### PR DESCRIPTION
**Pull request by NL66278**
Need date in statement id for camt, because some banks reuse id's in other years.

### CODE REVIEW

**Comment by NL66278** [comment]
Actually relevant tests run OK. Only error in travis is the permanent and seemingly unsolvable ofx module error.

**Comment by pedrobaeza** [comment]
The problem with this approach is that you can query the same statement in several different days, having a different execution time, so it would be imported twice, isn't it?

**Comment by NL66278** [comment]
@pedrobaeza If you query the same statement, all the lines will already have been imported, and so the import will be refused.

**Comment by pedrobaeza** [comment]
OK, and there's no chance that the line IDs are also reused?

**Comment by NL66278** [comment]
The line id's are by default composed of statement_id and line number in the statement. There is a problem when a customer imports several days for the same bank, where transactions in the statements overlap. Because of the different statement id, the duplication of transactions is not detected in that case. To solve that problem an alternative way to determine line uniqueness is provided by this PR: https://github.com/OCA/bank-statement-import/pull/77

**Comment by StefanRijnhart** [comment]
Thank you! :+1:

**Review by pedrobaeza — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
I see you cherry-picked the fix for the tests. That has been merged now. Can you rebase https://github.com/OCA/bank-statement-import/pull/83/commits/7c17c497d2ce1340f67d0833e49439dac0ebb328 onto 8.0 to get rid of the redundant commit?

**Comment by NL66278** [comment]
@StefanRijnhart Rebase done.

**Review by StefanRijnhart — APPROVED** [review]

**Pull request merged**
