### PR TITLE
[14.0] repo update fix pre-commit

### PR DESCRIPTION
**Pull request by bosd**
Fixes pre-commit on:
https://github.com/OCA/bank-statement-import/pull/645
https://github.com/OCA/bank-statement-import/pull/633

### CODE REVIEW

**Comment by bosd** [comment]
2nd commit fixes:
image
https://github.com/OCA/bank-statement-import/actions/runs/7519164891/job/20467399124?pr=658

**Comment by StefanRijnhart** [comment]
Can the invalid translations be fixed here (just add the 'new' `subsitution` variable at the end) or does that need to happen on Weblate?

**Review by StefanRijnhart — APPROVED** [review]
Love to see this green! Thanks!

**Review by Dranyel-Bosd — APPROVED** [review]
LGTM :+1:  :fireworks:

**Pull request merged**
