### PR TITLE
[9.0] [ENH] allow camt054 to be parsed

### PR DESCRIPTION
**Pull request by davidwul**
A small PR to allow camt054 to be parsed. 
camt054 are details of a grouped transaction that occurs in a camt053.
In CH, camt054 are grouped by day inside the camt [therefore the transaction grouping PR ](https://github.com/OCA/bank-statement-import/pull/102)is needed to import the camt054 successfully.

### CODE REVIEW

**Comment by ghost** [comment]
Worked smoothly when importing PostFinance camt054 manually as bank statements. The only problem is that the account balance is 0.0 because camt.054s aren't statements and don't contain that...

**Comment by davidwul** [comment]
@lbeopennet yes, allowing camt to parse 054 is just a start.
Adapting the balance is therefore one of the next things to do. 
Then if camt054 is in use, it means there is a transfer account and a journal to use for that purpose. All the configuration of that should be enhanced or eased somehow.
Also for control purpose, when importing camt054 (and camt053 with VCOM), a reconciliation could be automatically set between these moves using _AcctSvcrRef_

**Review by StefanRijnhart — APPROVED** [review]

**Review by ecino — APPROVED** [review]

**Comment by ecino** [comment]
👍 This one could be merged.

**Review by NL66278 — APPROVED** [review]
👍 LGTM

**Comment by eLBati** [comment]
backporting to 8.0 with https://github.com/OCA/bank-statement-import/pull/128

**Comment by eLBati** [comment]
@davidwul 
> This branch has conflicts that must be resolved
Conflicting files
account_bank_statement_import_camt/camt.py

Can you check?

**Comment by eLBati** [comment]
Porting to 10.0 with https://github.com/OCA/bank-statement-import/pull/133

**Comment by ecino** [comment]
@eLBati PR fixed.

**Review by eLBati — APPROVED** [review]
thanks

**Pull request merged**
