### PR TITLE
[15.0][IMP] account_statement_import_online_paypal: new paypal event_codes

### PR DESCRIPTION
**Pull request by ntsirintanis**
Related: https://github.com/OCA/bank-statement-import/pull/642

### CODE REVIEW

**Review by lfreeke — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
@ntsirintanis Thanks for the PR! Is there a chance you'd be willing to port that across the versions? Also, is there a `T0402` message?

**Comment by ntsirintanis** [comment]
> @ntsirintanis Thanks for the PR! Is there a chance you'd be willing to port that across the versions? Also, is there a `T0402` message?

Hoi Alexey, yes, there actually is:

`Transfer Withdrawal	T0402	Withdrawal to Hyperwallet	DR`

Though I am not quite sure if this is relevant to Odoo. Nevertheless, I can add another key.

**Comment by alexey-pelykh** [comment]
@ntsirintanis if that's not too troublesome, please add - there are a lot of keys that are probably irrelevant yet they are there. I'll fast-track the changes anyways

**Review by thomaspaulb — APPROVED** [review]

**Comment by pedrobaeza** [comment]
`[UPD]` > `[IMP]`

**Comment by ntsirintanis** [comment]
> @ntsirintanis if that's not too troublesome, please add - there are a lot of keys that are probably irrelevant yet they are there. I'll fast-track the changes anyways

Hi @alexey-pelykh , I've pushed more codes in all PRs

**Comment by alexey-pelykh** [comment]
@ntsirintanis thanks! I guess there's no reason having 2 commits for this, just squash them - otherwise looks awesome

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
