### PR TITLE
camt: parse the type of reference

### PR DESCRIPTION
**Pull request by ghost**
There's a node that contains a categorisation of what kind of reference the `ref` contains. This module extends the parser to read its value and the statement line model to store it.

### CODE REVIEW

**Comment by lbeopennet** [comment]
This is WIP, unit tests are not ready, , and I've not yet used it in production.

**Comment by davidwul** [comment]
out of curiosity what's the purpose of extracting the type of reference?

**Comment by ghost** [comment]
@davidwul If it says "ISR Reference", I arrange for it to be used for reconciliation. (That's Swiss specific and I'll PR l10n-switzerland soon) Point is to mimic the behaviour of the good old payment slip V11 importer without potentially crashing on non-ISR references.

**Comment by davidwul** [comment]
@lbeopennet Ok, while testing camt054 import (with ISR reference) I just [updated base_transaction_id](https://github.com/davidwul/bank-statement-reconcile/commit/67361807f1846fed7db0d906d489414847e193f9) (as you pointed in other thread). I guess it could be more elegant but so far it give good results. 
What matching strategy are you looking at except matching on ref instead name? 
Are you planning to add completion of partner before having the reconciliation proposition?

**Comment by StefanRijnhart** [comment]
Would it hurt to add this to the core parser, and if it does, would it make sense to encapsulate the core parser in an AbstractModel so that it's methods can be overridden in the usual way?

**Comment by ghost** [comment]
As is, the functionnality is self-contained and optional, so it's a good candidate for being a separate module imho.  It adds a database field, which is a cost that maybe not everyone who uses the core parser wants to pay, so I'd rather not force it into the core parser. Same goes for #105.  As for the `AbstractModel`, I hadn't thought of it and it's clever.  We use Plain Old Python Instance Attributes in the parser, but they seem to work on `Model`, as I've [superficially checked.](https://github.com/lbeopennet/bank-statement-import/commits/9.0%2Bcamt-reftype%2Bcamt-details_2) And it's probably safe to use since they instanciate a Python object [each time.](https://github.com/odoo/odoo/blob/9.0/openerp/models.py#L5381) Should we switch to that?

**Comment by StefanRijnhart** [comment]
I tend to think so. @hbrunn, any opinion on this matter? It's about making the camt parser class inheritable.

**Comment by hbrunn** [comment]
absolutely `AbstractModel`. Should have done that while migrating to some version, so if anyone would do the honors, I'll be happy to review it. Don't forget to add a few hooks in the middle of loops to make customizations simple

**Comment by ghost** [comment]
Excellent! I already did some work on this.  I can look into adding a few hooks later this week, then I'll ask for a review on #110.

**Comment by ghost** [comment]
rebase to take into account the merging of #110

**Pull request closed without merging**
